User:
  type: object
  config:
    fields:
      id:
        type: 'Int!'
      name:
        type: 'String!'
      email:
        type: 'String!'
      phoneNumber:
        type: 'Int!'
      cin:
        type: 'Int!'
      department:
        type: 'Department'
      products:
        type: '[Product]'